// plugin.cpp : Defines the entry point for the DLL application.
//

#include "stdafx.h"
#include "IPlugin.h"

#include <math.h>
#include <cmath>
#include <stdio.h>
#include <stdlib.h>
#include <iostream>//to use cout


using namespace std;


////////////////////////////////////////////////////////////////////////
// A concrete plugin implementation
////////////////////////////////////////////////////////////////////////

// Photo-Reactor Plugin class

//****************************************************************************
//This code has been generated by the Mediachance photo reactor Code generator.


#define AddParameter(N,S,V,M1,M2,T,D) {strcpy (pParameters[N].m_sLabel,S);pParameters[N].m_dValue = V;pParameters[N].m_dMin = M1;pParameters[N].m_dMax = M2;pParameters[N].m_nType = T;pParameters[N].m_dSpecialValue = D;}

#define GetValue(N) (pParameters[N].m_dValue)
#define GetValueY(N) (pParameters[N].m_dSpecialValue)

#define SetValue(N,V) {pParameters[N].m_dValue = V;}

#define GetBOOLValue(N) ((BOOL)(pParameters[N].m_dValue==pParameters[N].m_dMax))

// if it is not defined, then here it is
//#define RGB(r,g,b) ((COLORREF)(((BYTE)(r)|((WORD)((BYTE)(g))<<8))|(((DWORD)(BYTE)(b))<<16)))

#define PARAM_RADIUS	0
#define PARAM_THRESHOLD	1
#define NUMBER_OF_USER_PARAMS 2

#define MIN(a,b) (((a)<(b))?(a):(b))
#define MAX(a,b) (((a)>(b))?(a):(b))


class Plugin1 : public IPlugin	
{
public:

		//Plugin Icon:
	//you can add your own icon by creating 160x100 png file, naming it the same as plugin dll and then placing it in the plugins folder
	//otherwise a generic icon will be use


	//this is the title of the box in workspace. it should be short
	const char* GetTitle () const
	{
		return "Surface Blur";
	}
	
	// this will appear in the help pane, you can put your credits and short info
	const char* GetDescription () const
	{
		return "The Surface Blur algorithm was created by Sylvain Paris and Frédo Durand.  This is my take on this quick Bilateral type filter.  First the kernel is seperable into Vertical and Horizontal passes making it faster.  We are also making the math simplier than a Bilateral blur by removing the double exponent math of a Bilateral Blur.";
	}

	// BASIC PARAMETERS
	// number of inputs 0,1 or 2
	int GetInputNumber ()
	{
		return 1;
	}

	// number of outputs 0 or 1
	int GetOutputNumber ()
	{
		return 1;
	}

	int GetBoxColor ()
	{
		return RGB(44,78,119);
	}

	int GetTextColor ()
	{
		return RGB(165,236,255);
	}

	// width of the box in the workspace
	// valid are between 50 and 100
	int GetBoxWidth ()
	{
		return 80;
	}

	// set the flags
	// see the interedCounterace builder
	// ex: nFlag = FLAG_FAST_PROCESS | FLAG_HELPER;

	//FLAG_NONE same as zero	Default, no other flags set
	//FLAG_UPDATE_IMMEDIATELY	It is very fast process that can update immediately. When user turns the sliders on UI the left display will update
	//							Use Update Immediately only for fast and single loop processes, for example Desaturate, Levels.
	//FLAG_HELPER				It is an helper object. Helper objects will remain visible in Devices and they can react to mouse messages. Example: Knob, Monitor, Bridge Pin
	//FLAG_BINDING				Binding object, attach to other objects and can change its binding value. It never goes to Process_Data functions.  Example: Knob, Switch, Slider
	//FLAG_DUMMY				It is only for interedCounterace but never process any data. Never goes to Process_Data functions. Example: Text note
	//FLAG_SKIPFINAL			Process data only during designing, doesn't process during final export. Example: Monitor, Vectorscope 
	//FLAG_LONGPROCESS			Process that takes > 1s to finish. Long Process will display the Progress dialog and will prevent user from changing values during the process.
	//FLAG_NEEDSIZEDATA		    Process need to know size of original image, the zoom and what part of image is visible in the preview. When set the plugin will receive SetSizeData
	//FLAG_NEEDMOUSE			Process will receive Mouse respond data from the workplace. This is only if your object is interactive, for example Knob, Slider

	int GetFlags ()
	{
		// it is fast process
		//int nFlag = FLAG_UPDATE_IMMEDIATELY;
		
		int nFlag = FLAG_LONGPROCESS;

		return nFlag;
	}


	// User InteredCounterace Build
	// there is maximum 29 Parameters

	int GetUIParameters (UIParameters* pParameters)
	{

		// label, value, min, max, type_of_control, special_value
		// use the UI builder in the software to generate this
		AddParameter( PARAM_RADIUS ,"Radius", 5.0, 1.0, 100.0, TYPE_SLIDER, 0.0);
		AddParameter( PARAM_THRESHOLD ,"Color Difference", .255, 0.0, 1.0, TYPE_SLIDER, 0.0);

		return NUMBER_OF_USER_PARAMS;
	}
	


	// Actual processing function for 1 input
	//***************************************************************************************************
	// Both buffers are the same size
	// don't change the IN buffer or things will go bad for other objects in random fashion
	// the pBGRA_out comes already with pre-copied data from pBGRA_in
	// Note: Don't assume the nWidth and nHeight will be every run the same or that it contains the whole image!!!! 
	// This function receives buffer of the actual preview (it can be just a crop of image when zoomed in) and during the final calculation of the full buffer
	// this is where the image processing happens
	virtual void Process_Data (BYTE* pBGRA_out,BYTE* pBGRA_in, int nWidth, int nHeight, UIParameters* pParameters)
	{



		//List of Parameters
		float dRadius = GetValue(PARAM_RADIUS);// used to grab radius from control
		float dThreshold = GetValue(PARAM_THRESHOLD);

		int radius = (int)dRadius;//convert radius to an integer

		float colorspace = 255.0;

		float* horizonaltemp=new float[nWidth * nHeight * 4];// this is our tempory buffer to store image blurred horizonally
		float* temp = new float[nWidth * nHeight * 4];//working in the 0-1 range


		int widthminus = nWidth - 1;
		int heightminus = nHeight - 1;

		//place our image in a seperate array in the 0-1 range, where 0 is darkest and 1 is lightest
		for (int x = 0; x < nWidth; x++)
		{
			for (int y = 0; y < nHeight; y++)
			{
					int nIdx = x * 4 + y * 4 * nWidth;

					float red = pBGRA_in[nIdx + CHANNEL_R] / colorspace;
					float green = pBGRA_in[nIdx + CHANNEL_G] / colorspace;
					float blue = pBGRA_in[nIdx + CHANNEL_B] / colorspace;

					temp[nIdx + CHANNEL_R] = red;
					temp[nIdx + CHANNEL_G] = green;
					temp[nIdx + CHANNEL_B] = blue;
			}
		}

#pragma region			//test for proof that the image is in temp and blurred horizontally
/*
		for (int x = 0; x< nWidth; x++)
		{
			for (int y = 0; y< nHeight; y++)
			{
					int nIdx = x * 4 + y * 4 * nWidth;

					int nR = temp [nIdx + CHANNEL_R] * colorspace;
					int nG = temp [nIdx + CHANNEL_G] * colorspace;
					int nB = temp [nIdx + CHANNEL_B] * colorspace;

					pBGRA_out[nIdx + CHANNEL_R] = CLAMP255(nR);
					pBGRA_out[nIdx + CHANNEL_G] = CLAMP255(nG);
					pBGRA_out[nIdx + CHANNEL_B] = CLAMP255(nB);
			}
		}
*/
#pragma endregion


#pragma region		//blurs horizonally
		for(int y = 0; y < nHeight; y++)
		{
			for(int x = 0; x < nWidth; x++)
			{
				//clear your variables to process the pixel
				
				unsigned int nIdx1 = (x + y * nWidth) * 4;
				//(x + y * nWidth) * 4

				float centerred = temp[nIdx1 + CHANNEL_R];
				float centergreen = temp[nIdx1 + CHANNEL_G];
				float centerblue = temp[nIdx1 + CHANNEL_B];

				float difference = 0;// this is the difference between center pixel and sliding pixel

				//float sumred = 0;
				//float sumgreen = 0;
				//float sumblue = 0;
				//equilivant to r,g,b

				float redCounter = 0;
				float greenCounter = 0;
				float blueCounter = 0;

				double red = 0;
				double green = 0;
				double blue = 0;

				//This is our Kernel
				//accumulate colors
				for(int i = x - radius; i <= x + radius; i++)
				{
					unsigned int nIdx2 = (i + y * nWidth) * 4;

					if (i < 0 || i > widthminus) continue;
					{
						//this slides / moves along the kernel to collect the neighboring pixels
						float redKernelSlider   = temp[nIdx2 + CHANNEL_R];
						float greenKernelSlider = temp[nIdx2 + CHANNEL_G];
						float blueKernelSlider  = temp[nIdx2 + CHANNEL_B];
						//this slides / moves along the kernel to collect the neighboring pixels

						float factor = exp(-(i - x) * (i - x)/( 2 * radius * radius));

						difference = centerred - redKernelSlider;
                        if ( difference >= -dThreshold && difference <= dThreshold ) 
						{
							red += factor * redKernelSlider;
							redCounter++;
                        }

						difference = centergreen - greenKernelSlider;
                        if ( difference >= -dThreshold && difference <= dThreshold ) 
						{
							green += factor * greenKernelSlider;
							greenCounter++;
                        }

						difference = centerblue - blueKernelSlider;
                        if ( difference >= -dThreshold && difference <= dThreshold ) 
						{
							blue += factor * blueKernelSlider;
							blueCounter++;
                        }
					}
				}				

				red = redCounter == 0 ? centerred : red/redCounter;
                green = greenCounter == 0 ? centergreen : green/greenCounter;
                blue = blueCounter == 0 ? centerblue : blue/blueCounter;


				{//output
					horizonaltemp[nIdx1 + CHANNEL_R] = red;
					horizonaltemp[nIdx1 + CHANNEL_G] = green;
					horizonaltemp[nIdx1 + CHANNEL_B] = blue;
				}//end output
			}
		}
#pragma endregion


#pragma region			//test for proof that the image is in temp and blurred horizontally
/*
		for (int x = 0; x< nWidth; x++)
		{
			for (int y = 0; y< nHeight; y++)
			{
					int nIdx = x * 4 + y * 4 * nWidth;

					int nR = horizonaltemp [nIdx + CHANNEL_R] * colorspace;
					int nG = horizonaltemp [nIdx + CHANNEL_G] * colorspace;
					int nB = horizonaltemp [nIdx + CHANNEL_B] * colorspace;

					//pBGRA_out[nIdx + CHANNEL_R] = CLAMP255(nR);
					//pBGRA_out[nIdx + CHANNEL_G] = CLAMP255(nG);
					//pBGRA_out[nIdx + CHANNEL_B] = CLAMP255(nB);
			}
		}
*/
#pragma endregion



#pragma region		//blurs vertically
		for(int x = 0; x < nWidth; x++)
		{
			for(int y = 0; y < nHeight; y++)
			{
				//unsigned int ctrIdx = y * nWidth + x;
				unsigned int nIdx1 = (x + y * nWidth) * 4;

				float centerred = temp[nIdx1 + CHANNEL_R];
				float centergreen = temp[nIdx1 + CHANNEL_G];
				float centerblue = temp[nIdx1 + CHANNEL_B];

				float difference = 0;// this is the difference between center pixel and sliding pixel

				float redCounter = 0;
				float greenCounter = 0;
				float blueCounter = 0;

				double red = 0;
				double green = 0;
				double blue = 0;

				//This is our Kernel
				//accumulate colors
				for(int i = y - radius; i <= y + radius; i++)
				{
					if (i < 0 || i > heightminus) continue;
					{
						unsigned int nIdx2 = (x + i * nWidth) * 4;
						//this slides / moves along the kernel to collect the neighboring pixels
						float redKernelSlider   = horizonaltemp[nIdx2 + CHANNEL_R];
						float greenKernelSlider = horizonaltemp[nIdx2 + CHANNEL_G];
						float blueKernelSlider  = horizonaltemp[nIdx2 + CHANNEL_B];
						//this slides / moves along the kernel to collect the neighboring pixels

						float factor = exp(-(i - y) * (i - y) / (2 * radius * radius));

						difference = centerred - redKernelSlider;
                        if ( difference >= -dThreshold && difference <= dThreshold ) 
						{
							red += factor * redKernelSlider;
							redCounter++;
                        }

						difference = centergreen - greenKernelSlider;
                        if ( difference >= -dThreshold && difference <= dThreshold ) 
						{
							green += factor * greenKernelSlider;
							greenCounter++;
                        }

						difference = centerblue - blueKernelSlider;
                        if ( difference >= -dThreshold && difference <= dThreshold ) 
						{
							blue += factor * blueKernelSlider;
							blueCounter++;
                        }

					}
				}

				red = redCounter == 0 ? centerred : red/redCounter;
                green = greenCounter == 0 ? centergreen : green/greenCounter;
                blue = blueCounter == 0 ? centerblue : blue/blueCounter;


				{//output
					temp[nIdx1 + CHANNEL_R] = red;
					temp[nIdx1 + CHANNEL_G] = green;
					temp[nIdx1 + CHANNEL_B] = blue;
				}//end output
			}
		}
#pragma endregion









#pragma region			//test for proof that the image is in temp and blurred horizontally

		for (int x = 0; x< nWidth; x++)
		{
			for (int y = 0; y< nHeight; y++)
			{
					int nIdx = x * 4 + y * 4 * nWidth;
				
					//int nR = horizonaltemp [nIdx + CHANNEL_R] * colorspace;
					//int nG = horizonaltemp [nIdx + CHANNEL_G] * colorspace;
					//int nB = horizonaltemp [nIdx + CHANNEL_B] * colorspace;

					//int nR = verticaltemp [nIdx + CHANNEL_R] * colorspace;
					//int nG = verticaltemp [nIdx + CHANNEL_G] * colorspace;
					//int nB = verticaltemp [nIdx + CHANNEL_B] * colorspace;
					
					//int nR = ((horizonaltemp [nIdx + CHANNEL_R] + verticaltemp [nIdx + CHANNEL_R]) / 2.0f) * colorspace;
					//int nG = ((horizonaltemp [nIdx + CHANNEL_G] + verticaltemp [nIdx + CHANNEL_G]) / 2.0f) * colorspace;
					//int nB = ((horizonaltemp [nIdx + CHANNEL_B] + verticaltemp [nIdx + CHANNEL_B]) / 2.0f) * colorspace;

					int nR = temp [nIdx + CHANNEL_R] * colorspace;
					int nG = temp [nIdx + CHANNEL_G] * colorspace;
					int nB = temp [nIdx + CHANNEL_B] * colorspace;


					pBGRA_out[nIdx + CHANNEL_R] = CLAMP255(nR);
					pBGRA_out[nIdx + CHANNEL_G] = CLAMP255(nG);
					pBGRA_out[nIdx + CHANNEL_B] = CLAMP255(nB);
			}
		}

#pragma endregion


		delete [] temp;//delete the array
		delete [] horizonaltemp;//delete the array

	}//end routine


						


	// actual processing function for 2 inputs
	//********************************************************************************
	// all buffers are the same size
	// don't change the IN buffers or things will go bad
	// the pBGRA_out comes already with copied data from pBGRA_in1
	virtual void Process_Data2 (BYTE* pBGRA_out, BYTE* pBGRA_in1, BYTE* pBGRA_in2, int nWidth, int nHeight, UIParameters* pParameters)
	{

	}


	//*****************Drawing functions for the BOX *********************************
	//how is the drawing handled
	//DRAW_AUTOMATICALLY	the main program will fully take care of this and draw a box, title, socket and thumbnail
	//DRAW_SIMPLE_A			will draw a box, title and sockets and call CustomDraw
	//DRAW_SIMPLE_B			will draw a box and sockets and call CustomDraw
	//DRAW_SOCKETSONLY      will call CustomDraw and then draw sockets on top of it
	
	// highlighting rectangle around is always drawn except for DRAW_SOCKETSONLY

	virtual int GetDrawingType ()
	{

		int nType = DRAW_AUTOMATICALLY;

		return nType;

	}


	// Custom Drawing
	// custom drawing function called when drawing type is different than DRAW_AUTOMATICALLY
	// it is not always in real pixels but scaled depending on where it is drawn
	// the scale could be from 1.0 to > 1.0
	// so you always multiply the position, sizes, font size, line width with the scale
	
	virtual void CustomDraw (HDC hDC, int nX,int nY, int nWidth, int nHeight, float scale, BOOL bIsHighlighted, UIParameters* pParameters)
	{
	}


	//************ Optional Functions *****************************************************************************************
	// those functions are not necessary for normal effect, they are mostly for special effects and objects


	// Called when FLAG_HELPER set. 
	// When UI data changed (user turned knob) this function will be called as soon as user finish channging the data
	// You will get the latest parameters and also which parameter changed
	// Normally for effects you don't have to do anything here because you will get the same parameters in the process function
	// It is only for helper objects that may not go to Process Data 
	BOOL UIParametersChanged (UIParameters* pParameters, int nParameter)
	{
		
		return FALSE;
	}

	// when button is pressed on UI, this function will be called with the parameter and sub button (for multi button line)
	BOOL UIButtonPushed (int nParam, int nSubButton, UIParameters* pParameters)
	{

		return TRUE;
	}


	// Called when FLAG_NEEDSIZEDATA set
	// Called before each calculation (Process_Data)
	// If your process depends on a position on a frame you may need the data to correctly display it because Process_Data receives only a preview crop
	// Most normal effects don't depend on the position in frame so you don't need the data
	// Example: drawing a circle at a certain position requires to know what is displayed in preview or the circle will be at the same size and position regardless of zoom
	
	// Note: Even if you need position but you don't want to mess with the crop data, just ignore it and pretend the Process_Data are always of full image (they are not). 
	// In worst case this affects only preview when using zoom. The full process image always sends the whole data

	// nOriginalW, nOriginalH - the size of the original - full image. If user sets Resize on input - this will be the resized image
	// nPreviewW, nPreviewH   - this is the currently processed preview width/height - it is the same that Process_Data will receive
	//                        - in full process the nPreviewW, nPreviewH is equal nOriginalW, nOriginalH
	// Crop X1,Y1,X2,Y2       - relative coordinates of preview crop rectangle in <0...1>, for full process they are 0,0,1,1 (full rectangle)	
	// dZoom                  - Zoom of the Preview, for full process the dZoom = 1.0
	void SetSizeData(int nOriginalW, int nOriginalH, int nPreviewW, int nPreviewH, double dCropX1, double dCropY1, double dCropX2, double dCropY2, double dZoom)
	{

		// so if you need the position and zoom, this is the place to get it.
		// Note: because of IBM wisdom the internal bitmaps are on PC always upside down, but the coordinates are not


	}


	// ***** Mouse handling on workplace *************************** 
	// only if FLAG_NEEDMOUSE is set
	//****************************************************************
	//this is for special objects that need to receive mouse, like a knob or slider on workplace
	// normally you use this for FLAG_BINDING objects

	// in coordinates relative to top, left corner of the object (0,0)
	virtual BOOL MouseButtonDown (int nX, int nY, int nWidth, int nHeight, UIParameters* pParameters)
	{
		
		// return FALSE if not handled
		// return TRUE if handled
		return FALSE;
	}

	// in coordinates relative to top, left corner of the object (0,0)
	virtual BOOL MouseMove (int nX, int nY, int nWidth, int nHeight, UIParameters* pParameters)
	{
	

		return FALSE;
	}
	
	// in coordinates relative to top, left corner of the object (0,0)
	virtual BOOL MouseButtonUp (int nX, int nY, int nWidth, int nHeight, UIParameters* pParameters)
	{
		
		// Note: if we changed data and need to recalculate the flow we need to return TRUE

		// return FALSE if not handled
		// return TRUE if handled
		
		return TRUE;
	}


};

extern "C"
{
	// Plugin factory function
	__declspec(dllexport) IPlugin* Create_Plugin ()
	{
		//allocate a new object and return it
		return new Plugin1 ();
	}
	
	// Plugin cleanup function
	__declspec(dllexport) void Release_Plugin (IPlugin* p_plugin)
	{
		//we allocated in the factory with new, delete the passed object
		delete p_plugin;
	}
	
}


// this is the name that will appear in the object library
extern "C" __declspec(dllexport) char* GetPluginName()
{
	return "!@Andy's Surface Blur";	
}


// This MUST be unique string for each plugin so we can save the data

extern "C" __declspec(dllexport) char* GetPluginID()
{
	
	
	return "com.lumafilters.Surfaceblur2";
	
}


// category of plugin, for now the EFFECT go to top library box, everything else goes to the middle library box
extern "C" __declspec(dllexport) int GetCategory()
{
		
	return CATEGORY_EFFECT;
	
}
